# version: "3.8"
# services:
#   app:
#     container_name: video-analysis
#     image: video-analysis
#     build:
#       context: ./client
#       target: production
#     ports:
#       - "5002:80"
version: '3'
services:
  server:
    build: ./server
    ports:
      - 8080:8080
  client:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BASE_API_URL= http://54.221.73.168/api;
      - REACT_APP_BASE_NOTI_URL = http://54.221.73.168/noti;
