name: Server Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image Server
        run: |
            cd video-editing-api
            docker build -t 81quanghuy/videodemoserver:latest -f video-editing-api/Dockerfile .
            docker login -u 81quanghuy -p huyvff@111
            docker push 81quanghuy/videodemoserver:latest
          
