name: TestCI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd client
          npm install
      - name: Test
        run: |
          cd client
          npx jest --runInBand
#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: Jest Report
#           path: ./reports/html-report
