name: Cypress CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory to client
        run: cd client
      - name: Build and run tests
        working-directory: ./client
        run: |
          npm install
          npm run build
