name: TestCI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd client
          npm install
      - name: Test
        run: |
          cd client
          npx jest --runInBand 00TestLogin.test.js 000testSignUp.test.js 01TestAddMatch.test.js 02TestUploadVideo.test.js 03TestDownloadVideo.test.js 04TestUploadJson.test.js 05TestDeleteVideo.test.js 06TestSearchMatch.test.js 07TestSearchVideo.test.js 08TestDeleteMatch.test.js 09TestAddVideo.test.js 010TestLogout.test.js


      - name: Upload artifact and Generate Report
        uses: actions/upload-artifact@v2
        with:
          name: Jest Report
          path: client/reports/html-report/report.html
    

#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: Jest Report
#           path: ./reports/html-report
