name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          dir $GITHUB_WORKSPACE

      - name: Switch to Client Directory
        run: |
          cd $GITHUB_WORKSPACE/video-editing/client

      - name: Install dependencies
        run: npm install

      - name: Set environment variable
        run: echo "MY_VARIABLE=example-value" >> $GITHUB_ENV

      - name: Test
        run: npx jest Logout.test.js
